'use client'
import { useMemo, useState } from 'react'
import Papa from 'papaparse'
import { ArrowUpRight, Check, ChevronRight, Clock3, FileUp, Flame, MessageSquare, Search, Sparkles, Users, X, SlidersHorizontal, Trash2, UploadCloud } from 'lucide-react'

type Connection={first:string;last:string;url:string;company:string;position:string;connected:string}
type Message={from:string;sender:string;to:string;recipient:string;date:string;content:string;folder:string}
type Ranked=Connection & {score:number; reasons:string[]; action:'Reach out'|'Follow up'|'Keep warm'; lastOutgoing?:string; lastIncoming?:string; outgoingCount:number; incomingCount:number}
type FileItem={id:string;name:string;type:'connections'|'messages';rows:number;status:'ready'|'error';error?:string}

const ROLE_SYNONYMS:Record<string,string[]>={
 'product manager':['product','product manager','product management','pm','platform','growth','product strategy','product lead','product head','chief product','cpo'],
 'product':['product','product manager','product management','pm','platform','growth','product strategy','product lead','product head','chief product','cpo'],
 'software engineer':['engineer','engineering','software','developer','technology','tech lead','cto','technical'],
 'designer':['design','designer','ux','ui','product design','creative'],
 'marketing':['marketing','growth','brand','demand','communications','content','cmo'],
 'finance':['finance','financial','investment','investing','treasury','cfo','fp&a'],
}
const HIRING_TITLES=['founder','co-founder','ceo','chief executive','cpo','chief product','vp product','vice president product','head of product','product head','director product','head of talent','talent','recruiter','recruiting','human resources','hr','people','hiring manager','founding team','owner']
const LEADERSHIP=['founder','co-founder','ceo','cpo','cto','cfo','chief','vp ','vice president','head of','director','partner','owner','managing director']
function norm(s=''){return s.toLowerCase().replace(/[^a-z0-9+ ]/g,' ').replace(/\s+/g,' ').trim()}
function termsFor(target:string){const t=norm(target);for(const k of Object.keys(ROLE_SYNONYMS))if(t.includes(k))return ROLE_SYNONYMS[k];return t.split(' ').filter(x=>x.length>2).concat(['product','pm'])}
function parseDate(s=''){const d=Date.parse(s.replace(' UTC','Z'));return Number.isFinite(d)?d:0}
function daysAgo(s=''){const d=parseDate(s);return d?Math.max(0,Math.floor((Date.now()-d)/86400000)):9999}
function isSelf(m:Message){return norm(m.from)==='richi kothari'||norm(m.sender).includes('richi-kothari')}
function matchesPerson(m:Message,c:Connection){const u=norm(c.url);return (u&&(norm(m.sender)===u||norm(m.recipient)===u))||norm(m.to)===norm(`${c.first} ${c.last}`)||norm(m.from)===norm(`${c.first} ${c.last}`)}
function rank(c:Connection,msgs:Message[],target:string):Ranked{
 const pos=norm(c.position),company=norm(c.company),terms=termsFor(target),roleHits=terms.filter(t=>pos.includes(t)).length
 const roleMatch=roleHits>0,hiring=HIRING_TITLES.some(t=>pos.includes(t)),leadership=LEADERSHIP.some(t=>pos.includes(t)),relevant=roleMatch||hiring||leadership
 const pm=msgs.filter(m=>matchesPerson(m,c)).sort((a,b)=>parseDate(b.date)-parseDate(a.date)),outgoing=pm.filter(isSelf),incoming=pm.filter(m=>!isSelf(m))
 const lastOut=outgoing[0]?.date,lastIn=incoming[0]?.date,awaiting=!!lastOut&&(!lastIn||parseDate(lastOut)>parseDate(lastIn)),follow=awaiting&&daysAgo(lastOut!)>=7
 let score=25,reasons:string[]=[]
 if(roleMatch){score+=35;reasons.push(`Profile is relevant to ${target}`)}
 if(hiring){score+=28;reasons.push('Likely able to hire for this role')}else if(leadership){score+=18;reasons.push('Senior decision-maker at the company')}
 if(!pm.length){score+=10;reasons.push('No previous conversation — good for first outreach')}
 if(follow){score+=12;reasons.push(`You messaged ${daysAgo(lastOut!)} days ago with no reply`)}
 if(pm.length&&!follow&&lastIn)reasons.push('Has replied to you before')
 if(!relevant){score-=15;reasons.push('Lower relevance to your target')}
 return {...c,score:Math.max(1,Math.min(99,score)),reasons,lastOutgoing:lastOut,lastIncoming:lastIn,outgoingCount:outgoing.length,incomingCount:incoming.length,action:follow?'Follow up':relevant?'Reach out':'Keep warm'}
}
async function parseLinkedInCsv(file:File,matcher:(h:string[])=>boolean){
 const text=await file.text(),lines=text.split(/\r?\n/);let header=-1
 for(let i=0;i<Math.min(lines.length,40);i++){const row=(Papa.parse<string[]>(lines[i],{skipEmptyLines:false}).data?.[0]||[]).map(x=>String(x).trim());if(matcher(row)){header=i;break}}
 if(header<0)throw new Error('LinkedIn header not found. Make sure this is a Connections or Messages CSV export.')
 return Papa.parse<any>(lines.slice(header).join('\n'),{header:true,skipEmptyLines:true,transformHeader:h=>h.replace(/^\uFEFF/,'').trim()})
}
async function readConnections(file:File){const r=await parseLinkedInCsv(file,h=>h.includes('First Name')&&h.includes('Last Name')&&h.includes('Company')&&h.includes('Position'));return (r.data as any[]).map(x=>({first:String(x['First Name']||'').trim(),last:String(x['Last Name']||'').trim(),url:String(x.URL||'').trim(),company:String(x.Company||'').trim(),position:String(x.Position||'').trim(),connected:String(x['Connected On']||'').trim()})).filter(x=>x.first||x.last)}
async function readMessages(file:File){const r=await parseLinkedInCsv(file,h=>h.includes('CONVERSATION ID')&&h.includes('FROM')&&h.includes('TO')&&h.includes('CONTENT'));return (r.data as any[]).map(x=>({from:String(x.FROM||'').trim(),sender:String(x['SENDER PROFILE URL']||'').trim(),to:String(x.TO||'').trim(),recipient:String(x['RECIPIENT PROFILE URLS']||'').trim(),date:String(x.DATE||'').trim(),content:String(x.CONTENT||''),folder:String(x.FOLDER||'').trim()})).filter(x=>x.to||x.from)}
function dedupeConnections(rows:Connection[]){const map=new Map<string,Connection>();for(const c of rows){const key=norm(c.url)||norm(`${c.first} ${c.last} ${c.company}`);if(key&&!map.has(key))map.set(key,c)}return [...map.values()]}
function dedupeMessages(rows:Message[]){const seen=new Set<string>();return rows.filter(m=>{const k=`${m.date}|${m.from}|${m.to}|${m.content}`;if(seen.has(k))return false;seen.add(k);return true})}
function guessType(file:File){const n=file.name.toLowerCase();if(n.includes('message'))return'messages' as const;if(n.includes('connection'))return'connections' as const;return null}

export default function Home(){
 const [connections,setConnections]=useState<Connection[]>([]),[messages,setMessages]=useState<Message[]>([]),[files,setFiles]=useState<FileItem[]>([])
 const [target,setTarget]=useState('Product Manager'),[tab,setTab]=useState('Overview'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Ranked|null>(null),[notice,setNotice]=useState(''),[days,setDays]=useState(7),[drag,setDrag]=useState(false)
 const flash=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(''),2800)}
 const importFiles=async(fileList:FileList|File[])=>{for(const file of Array.from(fileList)){const id=`${file.name}-${file.size}-${file.lastModified}`;if(files.some(f=>f.id===id))continue;let type=guessType(file);try{if(!type){const text=await file.slice(0,16000).text();type=text.includes('CONVERSATION ID')?'messages':text.includes('First Name')?'connections':null}if(!type)throw new Error('Could not identify this LinkedIn export.');if(type==='connections'){const rows=await readConnections(file);setConnections(prev=>dedupeConnections([...prev,...rows]));setFiles(prev=>[...prev,{id,name:file.name,type,rows:rows.length,status:'ready'}]);flash(`${rows.length.toLocaleString()} connections added from ${file.name}`)}else{const rows=await readMessages(file);setMessages(prev=>dedupeMessages([...prev,...rows]));setFiles(prev=>[...prev,{id,name:file.name,type,rows:rows.length,status:'ready'}]);flash(`${rows.length.toLocaleString()} messages added from ${file.name}`)}}catch(e){const msg=e instanceof Error?e.message:'Could not read file';setFiles(prev=>[...prev,{id,name:file.name,type:type||'connections',rows:0,status:'error',error:msg}]);flash(`Couldn't import ${file.name}`)}}}
 const removeFile=(id:string)=>{setFiles(prev=>prev.filter(f=>f.id!==id));flash('File removed from the import list. Re-upload it to add its data again.')}
 const clearAll=()=>{setConnections([]);setMessages([]);setFiles([]);flash('Imported data cleared.')}
 const ranked=useMemo(()=>connections.map(c=>rank(c,messages,target)).sort((a,b)=>b.score-a.score),[connections,messages,target])
 const followups=ranked.filter(x=>x.action==='Follow up'&&x.lastOutgoing&&daysAgo(x.lastOutgoing)>=days),recommended=ranked.filter(x=>x.action==='Reach out').slice(0,6)
 const people=ranked.filter(c=>`${c.first} ${c.last} ${c.company} ${c.position}`.toLowerCase().includes(query.toLowerCase()))
 const companies=new Set(connections.map(c=>c.company).filter(Boolean)).size,contacted=ranked.filter(x=>x.outgoingCount>0).length,fresh=ranked.filter(x=>x.action==='Reach out').length
 const followDays=Math.min(...[7,10,14,21].map(x=>Math.abs(x-days)))
 return <main onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);importFiles(e.dataTransfer.files)}}>
  <aside className="sidebar"><div className="brand"><div className="brandmark">R</div><div><b>ReachOut</b><span>network copilot</span></div></div>
   <nav>{['Overview','People','Follow-ups'].map(x=><button key={x} className={tab===x?'nav active':'nav'} onClick={()=>setTab(x)}>{x==='Overview'?<Sparkles size={17}/>:x==='People'?<Users size={17}/>:<Clock3 size={17}/>}<span>{x}</span></button>)}</nav>
   <div className="sidebarBottom"><div className="miniTitle">YOUR SEARCH</div><label className="fieldLabel">Target role</label><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="e.g. Product Manager"/><div className="helper">We'll find people who match the role and people likely to hire for it.</div>
    <div className="miniTitle">YOUR DATA</div><label className="upload compact"><UploadCloud size={15}/><span>Import LinkedIn exports</span><input type="file" accept=".csv,text/csv" multiple onChange={e=>importFiles(e.target.files||[])}/></label>
    <div className="dataCounts"><span><b>{connections.length.toLocaleString()}</b> connections</span><span><b>{messages.length.toLocaleString()}</b> messages</span></div>
   </div>
  </aside>
  <section className="content"><header><div><div className="eyebrow">REACHOUT</div><h1>Know who to reach out to next.</h1><p>Your network, ranked around the role you're actually looking for.</p></div><div className="headerActions"><button className="ghost" onClick={()=>setTab('People')}><SlidersHorizontal size={15}/> All people</button><label className="primary"><FileUp size={15}/> Import data<input className="hidden" type="file" accept=".csv,text/csv" multiple onChange={e=>importFiles(e.target.files||[])}/></label></div></header>
   {notice&&<div className="toast"><Check size={15}/>{notice}</div>}
   {drag&&<div className="dropOverlay"><div><UploadCloud size={30}/><b>Drop LinkedIn exports here</b><span>Connections, messages, or both</span></div></div>}
   <section className="importPanel"><div className="importIntro"><div className="importIcon"><UploadCloud size={20}/></div><div><h2>Import your LinkedIn data</h2><p>LinkedIn splits your data across multiple CSVs. Upload <b>as many files as you have</b> — ReachOut will identify, combine and de-duplicate them automatically.</p></div><label className="importButton">Choose files<input type="file" accept=".csv,text/csv" multiple onChange={e=>importFiles(e.target.files||[])}/></label></div>
    <div className="fileTypes"><span><b>Connections</b> — who you know</span><span><b>Messages</b> — who you've contacted</span><span className="optional">You can upload files in any order</span></div>
    {files.length>0&&<div className="fileList">{files.map(f=><div className="fileRow" key={f.id}><div className={`fileDot ${f.status}`}>{f.status==='ready'?<Check size={12}/>:<X size={12}/>}</div><div className="fileName"><b>{f.name}</b><span>{f.status==='ready'?`${f.rows.toLocaleString()} rows imported · ${f.type}`:f.error}</span></div><button onClick={()=>removeFile(f.id)} aria-label="Remove file"><Trash2 size={14}/></button></div>)}<button className="clearBtn" onClick={clearAll}>Clear imported data</button></div>}
   </section>
   {tab==='Overview'&&<>
    <div className="targetBar"><div><span className="targetLabel">TARGET ROLE</span><strong>{target||'Add a target role'}</strong><small>Recommendations update as you type.</small></div><div className="targetPills"><span>Similar profiles</span><span>Potential hiring managers</span><span>Founders & leaders</span></div></div>
    <div className="stats"><Stat icon={<Users/>} value={connections.length.toLocaleString()} label="Connections imported"/><Stat icon={<MessageSquare/>} value={messages.length.toLocaleString()} label="Messages imported"/><Stat icon={<Flame/>} value={recommended.length} label="Top people now"/><Stat icon={<Clock3/>} value={followups.length} label="Follow-ups due"/></div>
    {!connections.length?<Empty title="Upload your LinkedIn exports to start" text="Add your Connections.csv and any Messages.csv files above. You can upload multiple dumps — ReachOut combines them automatically." onClick={()=>document.querySelector<HTMLInputElement>('.importPanel input[type=file]')?.click()}/>:<>
      <div className="sectionHead"><div><h2>Reach out now</h2><span>Highest-value people based on your target role and relationship history.</span></div><button className="textBtn" onClick={()=>setTab('People')}>See all <ChevronRight size={14}/></button></div>
      <div className="cards">{recommended.map(p=><PersonCard key={`${p.url}-${p.first}`} p={p} onClick={()=>setSelected(p)}/>)}</div>
      <div className="lower"><div className="sectionHead"><div><h2>Follow up</h2><span>People you've already messaged who may be worth nudging.</span></div><button className="textBtn" onClick={()=>setTab('Follow-ups')}>See all <ChevronRight size={14}/></button></div>
       {followups.length?<div className="followStrip">{followups.slice(0,5).map(p=><button key={`${p.url}-${p.first}`} onClick={()=>setSelected(p)}><div className="avatar">{(p.first[0]||'').toUpperCase()}{(p.last[0]||'').toUpperCase()}</div><div><b>{p.first} {p.last}</b><span>{p.position||'Role not listed'}{p.company?` · ${p.company}`:''}</span></div><span className="followBadge">{daysAgo(p.lastOutgoing!)}d since message</span><ChevronRight size={15}/></button>)}</div>:<div className="wideEmpty">No follow-ups due right now. We'll surface people automatically when they pass your follow-up window.</div>}
      </div>
    </>}
   </>}
   {tab==='People'&&<><div className="pageTitle"><div><h2>People</h2><span>{ranked.length.toLocaleString()} people ranked for {target}</span></div></div><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, company or role..."/></div><div className="table"><div className="tr th"><span>PERSON</span><span>COMPANY</span><span>ROLE</span><span>ACTION</span><span>SCORE</span></div>{people.slice(0,200).map(p=><button className="tr row" key={`${p.url}-${p.first}`} onClick={()=>setSelected(p)}><span><b>{p.first} {p.last}</b><small>{p.outgoingCount?p.outgoingCount+' sent':'No messages'}</small></span><span>{p.company||'—'}</span><span>{p.position||'—'}</span><span><i className={`action ${p.action==='Reach out'?'reach':p.action==='Follow up'?'follow':'warm'}`}>{p.action}</i></span><span className={p.score>=75?'hot':'warmScore'}>{p.score}</span></button>)}</div></>}
   {tab==='Follow-ups'&&<><div className="pageTitle"><div><h2>Follow-ups</h2><span>People you already contacted who are ready for a nudge.</span></div><label className="cadence">Follow up after <select value={followDays} onChange={e=>setDays(Number(e.target.value))}><option value={5}>5 days</option><option value={7}>7 days</option><option value={10}>10 days</option><option value={14}>14 days</option><option value={21}>21 days</option></select></label></div>{followups.length?<div className="followList">{followups.map(p=><button className="followRow" key={`${p.url}-${p.first}`} onClick={()=>setSelected(p)}><div className="avatar">{(p.first[0]||'').toUpperCase()}{(p.last[0]||'').toUpperCase()}</div><div className="followInfo"><b>{p.first} {p.last}</b><span>{p.position||'Role not listed'}{p.company?` · ${p.company}`:''}</span><small>Last message {daysAgo(p.lastOutgoing!)} days ago</small></div><div className="followReason">{p.reasons.find(r=>r.includes('days ago'))||'No reply since your last message.'}</div><ChevronRight size={16}/></button>)}</div>:<Empty title="You're all caught up" text={`No unanswered messages older than ${days} days. Change the follow-up window if you want a shorter or longer cadence.`}/>}</>}
  </section>
  {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><div className="profileAvatar">{(selected.first[0]||'').toUpperCase()}{(selected.last[0]||'').toUpperCase()}</div><h2>{selected.first} {selected.last}</h2><div className="role">{selected.position||'Role not listed'}{selected.company?` · ${selected.company}`:''}</div><div className="scoreBox"><div><small>REACHOUT SCORE</small><strong>{selected.score}</strong></div><span>{selected.action}</span></div><div className="why"><h3>WHY REACH OUT?</h3>{selected.reasons.slice(0,4).map(r=><div key={r}>✓ {r}</div>)}</div><div className="draft"><div className="draftHead"><b>{selected.action==='Follow up'?'Suggested follow-up':'Suggested opener'}</b><button onClick={()=>navigator.clipboard?.writeText(selected.action==='Follow up'?`Hey ${selected.first}, just following up on my note from ${selected.lastOutgoing||'recently'} — would love to connect when you have a moment.`:`Hey ${selected.first}, I came across your work at ${selected.company||'your company'} and wanted to reach out regarding my interest in ${target}. Would love to connect.`)}>Copy</button></div><p>{selected.action==='Follow up'?`Hey ${selected.first}, just following up on my note from ${selected.lastOutgoing||'recently'} — would love to connect when you have a moment.`:`Hey ${selected.first}, I came across your work at ${selected.company||'your company'} and wanted to reach out regarding my interest in ${target}. Would love to connect.`}</p></div><div className="history"><h3>Conversation history</h3>{messages.filter(m=>matchesPerson(m,selected)).slice(0,12).map((m,i)=><div className={`message ${isSelf(m)?'mine':''}`} key={i}><small>{isSelf(m)?'YOU':m.from} · {m.date}</small><p>{m.content}</p></div>)}{!messages.some(m=>matchesPerson(m,selected))&&<span className="muted">No messages found with this connection.</span>}</div></div></div>}
 </main>
}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string|number;label:string}){return <div className="stat"><div className="statIcon">{icon}</div><div><strong>{value}</strong><span>{label}</span></div></div>}
function PersonCard({p,onClick}:{p:Ranked;onClick:()=>void}){return <button className="personCard" onClick={onClick}><div className="cardTop"><div className="avatar">{(p.first[0]||'').toUpperCase()}{(p.last[0]||'').toUpperCase()}</div><div className="identity"><b>{p.first} {p.last}</b><span>{p.position||'Role not listed'}</span><small>{p.company||'Company not listed'}</small></div><div className="score"><strong>{p.score}</strong><span>SCORE</span></div></div><div className="reason"><Flame size={13}/>{p.reasons[0]}</div><div className="reasonList">{p.reasons.slice(1,3).map(r=><span key={r}>• {r}</span>)}</div><div className="cardAction"><span>{p.action}</span><ArrowUpRight size={14}/></div></button>}
function Empty({title,text,onClick}:{title:string;text:string;onClick?:()=>void}){return <div className="emptyPage"><div className="emptyIcon"><UploadCloud size={20}/></div><h3>{title}</h3><p>{text}</p>{onClick&&<button className="primary" onClick={onClick}>Import LinkedIn data</button>}</div>}
