'use client'
import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowUpRight, Check, ChevronRight, Clock3, FileUp, Flame, MessageSquare, Search, Sparkles, Users, X, RefreshCw, Trash2, UploadCloud, Target, UserRound, Database, AlertCircle } from 'lucide-react'

type Connection={first_name:string;last_name:string;linkedin_url:string;company:string;position:string;connected_on:string}
type Message={from:string;sender:string;to:string;recipient:string;date:string;content:string;folder:string}
type Ranked=Connection & {score:number;reasons:string[];action:'Reach out'|'Follow up'|'Keep warm';lastOutgoing?:string|null;lastIncoming?:string|null;outgoingCount:number;incomingCount:number}
type FileItem={id:string;name:string;type:'connections'|'messages'|null;rows:number;status:'ready'|'error'|'processing';error?:string}

const roleHints=['Product Manager','Product Designer','Software Engineer','Growth Manager','Investment Analyst']
function norm(s=''){return s.toLowerCase().replace(/[^a-z0-9+ ]/g,' ').replace(/\s+/g,' ').trim()}
function dateMs(s:string|null|undefined){if(!s)return 0;const d=Date.parse(s.replace(' UTC','Z'));return Number.isFinite(d)?d:0}
function daysAgo(s:string|null|undefined){const d=dateMs(s);return d?Math.max(0,Math.floor((Date.now()-d)/86400000)):9999}
function isSelf(m:Message, owner:string){return norm(m.from)===norm(owner)||norm(m.sender)===norm(owner)}
function matchesPerson(m:Message,c:Ranked){const url=norm(c.linkedin_url);return (!!url&&(norm(m.sender)===url||norm(m.recipient)===url))||norm(m.to)===norm(`${c.first_name} ${c.last_name}`)||norm(m.from)===norm(`${c.first_name} ${c.last_name}`)}

export default function Home(){
 const [connections,setConnections]=useState<Connection[]>([]),[messages,setMessages]=useState<Message[]>([]),[files,setFiles]=useState<FileItem[]>([]),[ranked,setRanked]=useState<Ranked[]>([])
 const [connectionCount,setConnectionCount]=useState(0),[messageCount,setMessageCount]=useState(0),[ownerName,setOwnerName]=useState('Richi Kothari'),[target,setTarget]=useState('Product Manager')
 const [tab,setTab]=useState<'Overview'|'People'|'Follow-ups'>('Overview'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Ranked|null>(null)
 const [notice,setNotice]=useState(''),[days,setDays]=useState(7),[drag,setDrag]=useState(false),[loading,setLoading]=useState(false),[dataError,setDataError]=useState(''),[setupOpen,setSetupOpen]=useState(true)
 const inputRef=useRef<HTMLInputElement>(null)
 const [userId,setUserId]=useState('')
 useEffect(()=>{const key='reachout-user-id';let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID();localStorage.setItem(key,id)}setUserId(id);const n=localStorage.getItem('reachout-owner-name');if(n)setOwnerName(n);const t=localStorage.getItem('reachout-target-role');if(t)setTarget(t)},[])
 const flash=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(''),3500)}
 const loadDashboard=async(retries=2)=>{if(!userId)return;setLoading(true);setDataError('');let last='Could not load your dashboard.';try{for(let attempt=0;attempt<=retries;attempt++){try{const r=await fetch(`/api/dashboard?userId=${encodeURIComponent(userId)}&ownerName=${encodeURIComponent(ownerName)}&target=${encodeURIComponent(target)}&days=${days}`,{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Dashboard request failed (${r.status})`);setConnectionCount(Number(d.connectionsCount||0));setMessageCount(Number(d.messagesCount||0));setRanked(Array.isArray(d.people)?d.people:[]);setConnections((d.people||[]).map((p:any)=>({first_name:p.first_name||'',last_name:p.last_name||'',linkedin_url:p.linkedin_url||'',company:p.company||'',position:p.position||'',connected_on:p.connected_on||''})));setFiles((d.imports||[]).map((x:any)=>({id:x.id,name:x.file_name,type:x.file_type,rows:Number(x.row_count||0),status:x.status==='error'?'error':'ready',error:x.error||undefined})));return}catch(e){last=e instanceof Error?e.message:String(e);if(attempt<retries)await new Promise(r=>setTimeout(r,700*(attempt+1)))}}throw new Error(last)}catch(e){const msg=e instanceof Error?e.message:last;setDataError(msg);flash(msg)}finally{setLoading(false)}}
 const importFiles=async(fileList:FileList|File[])=>{const incoming=Array.from(fileList).filter(f=>/\.csv$/i.test(f.name));if(!incoming.length){flash('Please select LinkedIn CSV files.');return}setDataError('');let imported=0;for(const file of incoming){const localId=`${file.name}-${file.size}-${file.lastModified}`;setFiles(prev=>prev.some(x=>x.id===localId)?prev:[...prev,{id:localId,name:file.name,type:null,rows:0,status:'processing'}]);try{const form=new FormData();form.append('userId',userId);form.append('file',file);let result:any;const direct=await fetch('/api/import/upload',{method:'POST',body:form});if(direct.ok)result=await direct.json();else if(direct.status===413){const sign=await fetch('/api/uploads/sign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,fileName:file.name})});const signed=await sign.json().catch(()=>({}));if(!sign.ok)throw new Error(signed.error||'Could not prepare the upload.');const up=await fetch(signed.signedUrl,{method:'PUT',headers:{'Content-Type':file.type||'text/csv'},body:file});if(!up.ok)throw new Error(`Storage upload failed (${up.status}).`);const proc=await fetch('/api/import/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,path:signed.path,fileName:file.name})});result=await proc.json().catch(()=>({}));if(!proc.ok)throw new Error(result.error||'Could not process the uploaded file.')}else{const d=await direct.json().catch(()=>({}));throw new Error(d.error||`Could not import ${file.name}.`)}setFiles(prev=>prev.map(x=>x.id===localId?{...x,type:result.type,rows:Number(result.rows||0),status:'ready',error:undefined}:x));imported++;flash(`${file.name}: ${Number(result.rows||0).toLocaleString()} rows imported`)}catch(e){const msg=e instanceof Error?e.message:'Import failed.';setFiles(prev=>prev.map(x=>x.id===localId?{...x,status:'error',error:msg}:x));flash(msg)}}if(imported){await loadDashboard(4);setSetupOpen(false)}}
 const removeFile=async(id:string)=>{try{const r=await fetch('/api/import/delete',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,importId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not remove import.');await loadDashboard();flash('Import removed.')}catch(e){flash(e instanceof Error?e.message:'Could not remove import.')}}
 const clearAll=async()=>{if(!confirm('Remove all imported LinkedIn data from ReachOut?'))return;try{const r=await fetch('/api/reset',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId})});const d=await r.json();if(!r.ok)throw new Error(d.error);setConnections([]);setMessages([]);setRanked([]);setMessageCount(0);setConnectionCount(0);setFiles([]);setSetupOpen(true);flash('Imported data cleared.')}catch(e){flash(e instanceof Error?e.message:'Could not clear data.')}}
 useEffect(()=>{if(!selected||!userId)return;fetch(`/api/people/messages?userId=${encodeURIComponent(userId)}&linkedinUrl=${encodeURIComponent(selected.linkedin_url||'')}`,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error())).then(d=>setMessages(d.messages||[])).catch(()=>setMessages([]))},[selected,userId])
 useEffect(()=>{if(!userId)return;localStorage.setItem('reachout-owner-name',ownerName);localStorage.setItem('reachout-target-role',target);const t=window.setTimeout(()=>loadDashboard(),450);return()=>window.clearTimeout(t)},[userId,ownerName,target,days])
 const followups=ranked.filter(x=>x.action==='Follow up'&&x.lastOutgoing&&daysAgo(x.lastOutgoing)>=days)
 const recommended=ranked.filter(x=>x.action==='Reach out').slice(0,6)
 const people=ranked.filter(c=>`${c.first_name} ${c.last_name} ${c.company} ${c.position}`.toLowerCase().includes(query.toLowerCase()))
 const companies=useMemo(()=>new Set(connections.map(c=>c.company).filter(Boolean)).size,[connections])
 const hasData=connectionCount>0||messageCount>0

 return <main className="app" onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);importFiles(e.dataTransfer.files)}}>
  <aside className="sidebar">
   <div className="brand"><div className="brandmark">R</div><div><b>ReachOut</b><span>network intelligence</span></div></div>
   <nav>{(['Overview','People','Follow-ups'] as const).map(x=><button key={x} className={tab===x?'nav active':'nav'} onClick={()=>setTab(x)}>{x==='Overview'?<Sparkles size={17}/>:x==='People'?<Users size={17}/>:<Clock3 size={17}/>}<span>{x}</span>{x==='Follow-ups'&&followups.length>0&&<em>{followups.length}</em>}</button>)}</nav>
   <div className="sidebarBottom"><div className="sideMetric"><span>NETWORK</span><b>{connectionCount.toLocaleString()}</b><small>connections</small></div><div className="sideMetric"><span>ACTIVITY</span><b>{messageCount.toLocaleString()}</b><small>messages</small></div><div className="sideFooter">Built around your network<br/>and the role you're pursuing.</div></div>
  </aside>

  <section className="content">
   <header className="topbar"><div><div className="eyebrow">NETWORK INTELLIGENCE</div><h1>{tab==='Overview'?'Know who to reach out to next.':tab}</h1><p>{tab==='Overview'?`Your network ranked around ${target || 'your target role'}.`:tab==='People'?'Every connection, prioritized by relevance and relationship.':'A focused queue of conversations worth following up on.'}</p></div><button className="refresh" onClick={()=>loadDashboard(3)} disabled={loading}><RefreshCw size={15} className={loading?'spin':''}/>{loading?'Refreshing':'Refresh'}</button></header>

   {notice&&<div className="toast"><Check size={15}/>{notice}</div>}
   {dataError&&<div className="dataError"><AlertCircle size={16}/><div><b>We imported your files, but the dashboard needs another refresh.</b><span>{dataError}</span></div><button onClick={()=>loadDashboard(4)}>Retry</button></div>}

   <section className={`workspace ${setupOpen?'open':''}`}>
    <div className="workspaceHead"><div className="workspaceTitle"><div className="workspaceIcon"><Database size={19}/></div><div><div className="sectionEyebrow">WORKSPACE SETUP</div><h2>Connect your LinkedIn data</h2><p>One place for your profile, target role, and LinkedIn exports. ReachOut handles the rest.</p></div></div><button className="collapse" onClick={()=>setSetupOpen(!setupOpen)}>{setupOpen?'Hide':'Edit setup'}</button></div>
    {setupOpen&&<div className="setupGrid">
      <div className="setupField"><label><UserRound size={14}/> Your name</label><input value={ownerName} onChange={e=>setOwnerName(e.target.value)} placeholder="Your name"/><small>Used to identify messages you sent.</small></div>
      <div className="setupField"><label><Target size={14}/> Target role</label><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="e.g. Product Manager"/><div className="chips">{roleHints.slice(0,4).map(r=><button key={r} onClick={()=>setTarget(r)}>{r}</button>)}</div></div>
      <div className="uploadZone" onClick={()=>inputRef.current?.click()} onDragOver={e=>{e.preventDefault();e.stopPropagation()}}><input ref={inputRef} type="file" accept=".csv,text/csv" multiple hidden onChange={e=>importFiles(e.target.files||[])} /><div className="uploadIcon"><UploadCloud size={20}/></div><div><b>Import LinkedIn exports</b><span>Select <strong>Connections.csv</strong> and <strong>messages.csv</strong> together</span><small>Multiple files · automatic detection · de-duplication</small></div><button onClick={e=>{e.stopPropagation();inputRef.current?.click()}}>Choose files</button></div>
    </div>}
    {files.length>0&&<div className="importedFiles">{files.map(f=><div className="importedFile" key={f.id}><div className={`fileStatus ${f.status}`}>{f.status==='processing'?<RefreshCw size={12} className="spin"/>:f.status==='ready'?<Check size={12}/>:<X size={12}/>}</div><div><b>{f.name}</b><span>{f.status==='ready'?`${f.rows.toLocaleString()} rows · ${f.type}`:f.status==='processing'?'Importing…':f.error}</span></div>{f.status!=='processing'&&<button onClick={()=>removeFile(f.id)}><Trash2 size={14}/></button>}</div>)}<button className="clearBtn" onClick={clearAll}>Clear imported data</button></div>}
   </section>

   {tab==='Overview'&&<>
      <div className="stats"><Stat icon={<Users/>} value={connectionCount.toLocaleString()} label="Connections"/><Stat icon={<MessageSquare/>} value={messageCount.toLocaleString()} label="Messages"/><Stat icon={<Flame/>} value={recommended.length} label="High-priority people"/><Stat icon={<Clock3/>} value={followups.length} label="Follow-ups due"/></div>
      <section className="insightBar"><div><span className="sectionEyebrow">CURRENT SEARCH</span><b>{target || 'No target role set'}</b><span>{companies.toLocaleString()} companies represented in your network</span></div><div className="signalList"><span>Role relevance</span><span>Hiring influence</span><span>Relationship history</span></div></section>
      {hasData?<><div className="dashboardReady"><div><span className="sectionEyebrow">YOUR DASHBOARD</span><h2>Your network is loaded.</h2><p>{connectionCount.toLocaleString()} connections and {messageCount.toLocaleString()} messages are being used to prioritize your next outreach.</p></div><button className="textBtn" onClick={()=>setSetupOpen(true)}>Edit setup <ChevronRight size={14}/></button></div>
      <div className="sectionHead"><div><span className="sectionEyebrow">PRIORITIZED FOR YOU</span><h2>Reach out now</h2><p>People with the strongest combination of role fit, influence, and relationship opportunity.</p></div><button className="textBtn" onClick={()=>setTab('People')}>View all people <ChevronRight size={14}/></button></div>
      {recommended.length?<div className="cards">{recommended.map(p=><PersonCard key={`${p.linkedin_url}-${p.first_name}`} p={p} onClick={()=>setSelected(p)}/>)}</div>:<div className="wideEmpty"><Flame size={18}/><b>No high-priority matches yet</b><span>Try a more specific target role above.</span></div>}
      <div className="lower"><div className="sectionHead"><div><span className="sectionEyebrow">RELATIONSHIP QUEUE</span><h2>Follow up</h2><p>People you've contacted who haven't replied within your follow-up window.</p></div><button className="textBtn" onClick={()=>setTab('Follow-ups')}>View follow-ups <ChevronRight size={14}/></button></div>{followups.length?<div className="followStrip">{followups.slice(0,5).map(p=><button key={`${p.linkedin_url}-${p.first_name}`} onClick={()=>setSelected(p)}><div className="avatar">{initials(p)}</div><div><b>{p.first_name} {p.last_name}</b><span>{p.position||'Role not listed'}{p.company?` · ${p.company}`:''}</span></div><span className="followBadge">{daysAgo(p.lastOutgoing!)}d</span><ChevronRight size={15}/></button>)}</div>:<div className="wideEmpty"><Clock3 size={18}/><b>You're all caught up</b><span>No unanswered messages older than {days} days.</span></div>}</div>
      </>:<section className="welcome"><div className="welcomeGraphic"><Sparkles size={22}/></div><div><span className="sectionEyebrow">YOUR DASHBOARD</span><h2>Your network, made actionable.</h2><p>Import your LinkedIn Connections and messages above. Once they are processed, this dashboard will show your network size, outreach recommendations and follow-ups.</p><div className="welcomeSteps"><span><b>01</b> Import data</span><span><b>02</b> Set your target</span><span><b>03</b> Reach out</span></div></div></section>}
   </>}

   {tab==='People'&&<><div className="pageTitle"><div><span className="sectionEyebrow">NETWORK</span><h2>People</h2><p>{ranked.length.toLocaleString()} connections ranked for {target}</p></div></div><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people, companies or roles…"/></div><div className="table"><div className="tr th"><span>PERSON</span><span>COMPANY</span><span>ROLE</span><span>ACTION</span><span>SCORE</span></div>{people.slice(0,250).map(p=><button className="tr row" key={`${p.linkedin_url}-${p.first_name}`} onClick={()=>setSelected(p)}><span><b>{p.first_name} {p.last_name}</b><small>{p.outgoingCount?p.outgoingCount+' sent':'No messages'}</small></span><span>{p.company||'—'}</span><span>{p.position||'—'}</span><span><i className={`action ${p.action==='Reach out'?'reach':p.action==='Follow up'?'follow':'warm'}`}>{p.action}</i></span><span className={p.score>=75?'hot':'warmScore'}>{p.score}</span></button>)}</div></>}
   {tab==='Follow-ups'&&<><div className="pageTitle followHeader"><div><span className="sectionEyebrow">RELATIONSHIP QUEUE</span><h2>Follow-ups</h2><p>Conversations that are waiting for a response.</p></div><label>Follow up after <select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={5}>5 days</option><option value={7}>7 days</option><option value={10}>10 days</option><option value={14}>14 days</option><option value={21}>21 days</option></select></label></div>{followups.length?<div className="followList">{followups.map(p=><button className="followRow" key={`${p.linkedin_url}-${p.first_name}`} onClick={()=>setSelected(p)}><div className="avatar">{initials(p)}</div><div className="followInfo"><b>{p.first_name} {p.last_name}</b><span>{p.position||'Role not listed'}{p.company?` · ${p.company}`:''}</span><small>Last message {daysAgo(p.lastOutgoing!)} days ago</small></div><div className="followReason">{p.reasons.find(r=>r.includes('days ago'))||'No reply since your last message.'}</div><ChevronRight size={16}/></button>)}</div>:<div className="emptyPage"><div className="emptyIcon"><Check size={20}/></div><h3>You're all caught up</h3><p>No unanswered messages older than {days} days.</p></div>}</>}
  </section>
  {drag&&<div className="dropOverlay"><div><UploadCloud size={30}/><b>Drop your LinkedIn exports</b><span>Connections.csv and messages.csv</span></div></div>}
  {selected&&<Drawer selected={selected} ownerName={ownerName} target={target} messages={messages} close={()=>setSelected(null)}/>} 
 </main>
}
function initials(p:Connection){return `${(p.first_name[0]||'').toUpperCase()}${(p.last_name[0]||'').toUpperCase()}`||'?'}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string|number;label:string}){return <div className="stat"><div className="statIcon">{icon}</div><div><strong>{value}</strong><span>{label}</span></div></div>}
function PersonCard({p,onClick}:{p:Ranked;onClick:()=>void}){return <button className="personCard" onClick={onClick}><div className="cardTop"><div className="avatar">{initials(p)}</div><div className="identity"><b>{p.first_name} {p.last_name}</b><span>{p.position||'Role not listed'}</span><small>{p.company||'Company not listed'}</small></div><div className="score"><strong>{p.score}</strong><span>SCORE</span></div></div><div className="reason"><Flame size={13}/>{p.reasons[0]||'Potentially relevant to your search'}</div><div className="reasonList">{p.reasons.slice(1,3).map(r=><span key={r}>• {r}</span>)}</div><div className="cardAction"><span>{p.action}</span><ArrowUpRight size={14}/></div></button>}
function Drawer({selected,ownerName,target,messages,close}:{selected:Ranked;ownerName:string;target:string;messages:Message[];close:()=>void}){const mine=(m:Message)=>isSelf(m,ownerName);const conversation=messages.filter(m=>matchesPerson(m,selected)).slice(0,14);const opener=`Hey ${selected.first_name}, I came across your work at ${selected.company||'your company'} and wanted to reach out regarding my interest in ${target}. Would love to connect.`;const follow=`Hey ${selected.first_name}, just following up on my note from ${selected.lastOutgoing||'recently'} — would love to connect when you have a moment.`;const draft=selected.action==='Follow up'?follow:opener;return <div className="overlay" onClick={close}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><div className="profileAvatar">{initials(selected)}</div><h2>{selected.first_name} {selected.last_name}</h2><div className="role">{selected.position||'Role not listed'}{selected.company?` · ${selected.company}`:''}</div><div className="scoreBox"><div><small>REACHOUT SCORE</small><strong>{selected.score}</strong></div><span>{selected.action}</span></div><div className="why"><h3>WHY THIS PERSON</h3>{selected.reasons.slice(0,4).map(r=><div key={r}>✓ {r}</div>)}</div><div className="draft"><div className="draftHead"><b>{selected.action==='Follow up'?'Suggested follow-up':'Suggested opener'}</b><button onClick={()=>navigator.clipboard?.writeText(draft)}>Copy</button></div><p>{draft}</p></div><div className="history"><h3>Conversation history</h3>{conversation.map((m,i)=><div className={`message ${mine(m)?'mine':''}`} key={i}><small>{mine(m)?'YOU':m.from} · {m.date}</small><p>{m.content}</p></div>)}{!conversation.length&&<span className="muted">No messages found with this connection.</span>}</div></div></div>}
